### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by dmb107** [ychenracing/flyvar#1]
Hi, I would love to access the database. Is the website functional?
![screen shot 2016-11-15 at 4 59 21 pm](https://cloud.githubusercontent.com/assets/8741841/20326029/00240f3e-ab55-11e6-835d-0c6831691490.png)

**Comment by ychenracing** [comment]
I didn't notice that. I asked my teacher, she said the server is migrating. The website is not available in a period of time. 

If you are interested in flyvar, I suggest the paper [FlyVar](https://www.ncbi.nlm.nih.gov/pubmed/26289428). I will send a message to you once the site is available.

**Comment by dmb107** [comment]
Great, thank you!

Sent from my iPhone

On Nov 15, 2016, at 9:09 PM, ychenracing <notifications@github.com<mailto:notifications@github.com>> wrote:

I didn't notice that. I asked my teacher, she said the server is migrating. The website is not available in a period of time.

If you are interested in flyvar, I suggest the paper FlyVarhttps://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncbi.nlm.nih.gov_pubmed_26289428&d=DgMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=uGUQbUjGCnJLvpf4l5NzVw&m=Rm6N-3Cj0nuSyMGbZR5mlDCnodyVkQE8USx1nAH26UI&s=Q8LbopU5jBC8kWiwWUmyZKdctirPecHO9gzS36xAauk&e=. I will send a message to you once the site is available.

##

**Comment by ychenracing** [comment]
Hi, [FlyVar](http://www.iipl.fudan.edu.cn/FlyVar/) finished migrating. It is available now. 

As you can see, Query and Filter modules work fine. However, I found bugs in variation annotation module. I'll fix them in some days.

**Comment by dmb107** [comment]
Great, thank you for letting me know!

Sent from my iPhone

On Nov 21, 2016, at 4:41 AM, ychenracing <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, FlyVarhttps://urldefense.proofpoint.com/v2/url?u=http-3A__www.iipl.fudan.edu.cn_FlyVar_&d=DgMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=uGUQbUjGCnJLvpf4l5NzVw&m=a-kJusbqrcnZz7kdG6iVm_vj30uOSDy5JRdyQu5rBGw&s=pabU3JuKccd9uvCGX09CfzLrgcoJrEhr1Qx7Z4l_8YI&e= finished migrating. It is available now.

As you can see, Query and Filter modules work fine. However, I found bugs in variation annotation module. I'll fix them in some days.

##
